router id 10.255.0.6;

protocol device { }

protocol kernel {
    ipv4 { import none; export all; };
}

protocol ospf v2 ospf1 {
    ipv4 { import all; export all; };
    area 0 {
        interface "eth1" { type ptp; cost 10; hello 2; dead 8; };
        interface "eth2" { type ptp; cost 10; hello 2; dead 8; };
        interface "lo" { stub yes; };
    };
}
