router id 10.255.0.7;

protocol device { }

protocol direct {
    ipv4;
    interface "eth1", "eth2", "eth3", "eth4", "lo";
}

protocol kernel {
    ipv4 { import none; export where source = RTS_RIP; };
}

protocol rip rip1 {
    ipv4 { import all; export all; };
    interface "eth1" { version 2; update time 5; timeout time 20; garbage time 20; };
    interface "eth2" { version 2; update time 5; timeout time 20; garbage time 20; };
    interface "eth3" { version 2; update time 5; timeout time 20; garbage time 20; };
    interface "eth4" { passive; };
}
